hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path("tirth",views.tirth, name="tirth"),
    path("janki", views.janki, name="janki"),
    path("<str:name>", views.greet, name = "greet")
]

lecture3/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include("hello.urls")),
    path('newyear/',include("newyear.urls")),
    path('tasks/',include("tasks.urls"))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add" , views.add,name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from http.client import HTTPResponse
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"hello/index.html")
 
def tirth(request):
     return HttpResponse("Hello Tirth.")

def janki(request):
    return HttpResponse("Hello Janki.")

def greet(request,name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
from django.shortcuts import render
import datetime 

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html",{
        "newyear": now.date == 1 and now.month == 1
    })

tasks/views.py
from django.urls import reverse
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render


tasks = []

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task", max_length=100)
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)
    # category = forms.CharField(label="Category", max_length=100)

# Create your views here.

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request,"tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else :
            return render(request, "tasks/add.html", {
                "form":form
            })

    return render(request, "tasks/add.html" , {
        "forms": NewTaskForm()
    })

templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hello, {{ name }} !!!!!!</h1>
</body>

</html>

templates/hello/index.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hello World</h1>
    <h2>Welcome</h2>
</body>

</html>

templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it a new Year</title>
    <link rel="stylesheet" href="{%static 'newyear/style.css' %}">
</head>

<body>
    {% if newyear %}
    <h1>Yes, it is a new year</h1>
    {% else %}
    <h1>No, it is not a new year</h1>
    {% endif %}
</body>

</html>

templates/tasks/add.html
{% extends "tasks/layout.html" %} {% block body %}

<h2>Add Task</h2>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %} {{ forms }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">View Task</a> {% endblock %}

templates/tasks/index.html
{% extends "tasks/layout.html" %} {% block body %}
<ul>
    <h1>Tasks</h1>
    {% for task in tasks %}
    <li>{{ task }}</li>
    {% empty %}
    <li>No tasks</li>
    {% endfor %}
</ul>

<a href="{% url 'tasks:add' %}">Add a New Task</a> {% endblock %}

templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add TO DO</title>
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>